export const LOAD_PASSANGER_SUCCESS = "LOAD_PASSANGER_SUCCESS";
export const CREATE_PASSANGER_SUCCESS = "CREATE_PASSANGER_SUCCESS";
export const UPDATE_PASSANGER_SUCCESS = "UPDATE_PASSANGER_SUCCESS";
export const DELETE_PASSANGER_OPTIMISTIC = "DELETE_PASSANGER_OPTIMISTIC";
export const FILTER_PASSANGER_FLIGHT = "FILTER_PASSANGER_FLIGHT ";
export const RESET_FILTER_PASSANGER_FLIGHT = "RESET_FILTER_PASSANGER_FLIGHT";
export const UPDATE_ANCILLARY_PASSANGER_SUCCESS =
  "UPDATE_ANCILLARY_PASSANGER_SUCCESS";

export const LOAD_ANCILLARY_SUCCESS = "LOAD_ANCILLARY_SUCCESS";
export const CREATE_ANCILLARY_SUCCESS = "CREATE_ANCILLARY_SUCCESS";
export const UPDATE_ANCILLARY_SUCCESS = "UPDATE_ANCILLARY_SUCCESS";
export const DELETE_ANCILLARY_OPTIMISTIC = "DELETE_ANCILLARY_OPTIMISTIC";

export const LOAD_FLIGHT_SUCCESS = "LOAD_FLIGHT_SUCCESS";
export const LOAD_FLIGHT_NAME = "LOAD_FLIGHT_NAME";
export const CREATE_FLIGHT_SUCCESS = "CREATE_FLIGHT_SUCCESS";
export const UPDATE_FLIGHT_SUCCESS = "UPDATE_FLIGHT_SUCCESS";
export const UPDATE_ANCILLARY_FLIGHT_SUCCESS =
  "UPDATE_ANCILLARY_FLIGHT_SUCCESS";

export const CHOSEN_FLIGHT_NAME_SUCCESS = "CHOSEN_FLIGHT_NAME_SUCCESS";
export const CLEAR_CHOSEN_FLIGHT_NAME = "CLEAR_CHOSEN_FLIGHT_NAME";
export const GET_CHOSEN_FLIGHT_NAME = "GET_CHOSEN_FLIGHT_NAME";
