const passanger = [
  {
    name: "Rounaq",
    id: 1,
    age: 30,
    dateOfBirth: "25/07/1989",
    passportNumber: "R105070",
    flightName: "Air Asia",
    seatNo: "1",
    address: "Chennai",
    travelDate: "23/10/2019",
    ancillaryService: ["Extra 20 kg baggage", "lodging"],
    wheelChair: true,
    isCheckedIn: false,
    isHavingInfant: false,
    meals: "Veg",
    isSpecialMeals: true,
    shoppingItems: ["face cream", "hair gel"],
  },
  {
    name: "praveen",
    id: 2,
    age: 30,
    dateOfBirth: "25/07/1989",
    passportNumber: "R105070",
    flightName: "Air Asia",
    seatNo: "2",
    address: "Chennai",
    travelDate: "23/10/2019",
    ancillaryService: ["Extra 20 kg baggage", "lodging"],
    wheelChair: true,
    isCheckedIn: true,
    isHavingInfant: false,
    meals: "Veg",
    isSpecialMeals: false,
    shoppingItems: ["face cream", "hair gel"],
  },
  {
    name: "Nasrul",
    id: 3,
    age: 27,
    dateOfBirth: "05/06/1992",
    passportNumber: "N124081",
    address: "Bangalore",
    flightName: "Air Asia",
    seatNo: "3",
    travelDate: "23/10/2019",
    ancillaryService: ["Extra 10 kg baggage"],
    wheelChair: false,
    isCheckedIn: true,
    isHavingInfant: false,
    meals: "NonVeg",
    isSpecialMeals: true,
    shoppingItems: ["face wash"],
  },
  {
    name: "Aman",
    id: 4,
    age: 21,
    dateOfBirth: "16/02/1997",
    passportNumber: "A154489",
    flightName: "Indigo",
    address: "Delhi",
    seatNo: "4",
    travelDate: "23/10/2019",
    ancillaryService: ["lodging", "cab Services"],
    wheelChair: false,
    isCheckedIn: true,
    isHavingInfant: true,
    meals: "NonVeg",
    isSpecialMeals: false,
    shoppingItems: ["liquid makeup", "hair gel", "pencils"],
  },
];

const flight = [
  {
    name: "Air Asia",
    id: 1,
    ancillaryService: ["baggae", "accomoda"],
    meals: ["briyani", "rice"],
    totalSeats: 180,
    shoppingItems: [],
    destination: "",
    departureTime: "",
  },
  {
    name: "Indigo",
    id: 2,
    ancillaryService: [],
    meals: [],
    totalSeats: 200,
    shoppingItems: [],
    destination: "",
    departureTime: "",
  },
  {
    name: "Jet Airways",
    id: 3,
    ancillaryService: [],
    meals: [],
    totalSeats: 210,
    shoppingItems: [],
    destination: "",
    departureTime: "",
  },
  {
    name: "Go Air",
    id: 4,
    ancillaryService: [],
    totalSeats: 170,
    meals: [],
    shoppingItems: [],
    destination: "",
    departureTime: "",
  },
];

const ancillary = [
  {
    name: "20Kg Baggage",
    id: 1,
    description: "Extra 20Kg Baggage",
    type: { others: true },
    typeValue: "Others",
  },
  {
    name: "accommodation",
    id: 2,
    description: "Free accommodation",
    type: { others: true },
    typeValue: "others",
  },
  {
    name: "wine",
    id: 3,
    description: "Foreign Wine",
    type: { shoppingItem: true },
    typeValue: "shoppingItem",
  },
  {
    name: "hair gel",
    id: 4,
    description: "Himalayan hair gel",
    type: { shoppingItem: true },
    typeValue: "shoppingItem",
  },
  {
    name: "Briyani",
    id: 5,
    description: "Meals",
    type: { specialMeal: true },
    typeValue: "specialMeal",
  },
];

const user = [
  {
    username: "admin",
    id: 1,
    name: "Admin User",
    role: "Admin",
    password: "admin",
  },
  {
    username: "user",
    id: 2,
    name: "AirLine User",
    role: "User",
    password: "user",
  },
];

const newPassanger = {
  name: "",
  id: null,
  age: null,
  dateOfBirth: "",
  passportNumber: "",
  flightName: "",
  seatNo: "",
  address: "",
  travelDate: "",
  ancillaryService: [],
  wheelChair: false,
  isCheckedIn: false,
  isHavingInfant: false,
  meals: "",
  isSpecialMeals: false,
  shoppingItems: [],
};

const newAncillary = {
  name: "",
  id: null,
  description: "",
  type: {},
  typeValue: "",
};

const newFlight = {
  name: "",
  id: null,
  ancillaryService: [],
  meals: [],
  totalSeats: null,
  shoppingItems: [],
  destination: "",
  departureTime: "",
};

// Using CommonJS style export so we can consume via Node (without using Babel-node)
module.exports = {
  newPassanger,
  newAncillary,
  newFlight,
  passanger,
  flight,
  ancillary,
  user,
};
